#!/usr/bin/env ansible-playbook

- name: 'install.yml'          # quote names for syntax highlighting
  hosts: localhost             # scope the play appropriately
  connection: local            # 
  gather_facts: False          # booleans: /^(y|yes|n|no|true|false|on|off)$/i

  vars:                        
    - url: "https://galaxy.ansible.com"  

  tasks:                       # list tasks, but consider using a role
    - name: 'check network'    # format parameters for small terminal size
      uri: url={{ url }}     
           method=HEAD
           return_content=no
           status_code=200
           timeout=60
           follow_redirects=all

    - name: 'import roles from Galaxy and/or Git'
      command: ansible-galaxy install -r roles/requirements.yml
 
    - name: 'update Ansible rpm'
      become: yes
      yum: name=ansible state=latest

    - name: 'ensure permissions on ssh private key file'
      file: name=/home/vagrant/project/vagrant.rsa state=file mode=0600

    - name: 'ensure permissions on directory'
      file: name=/home/vagrant/project state=directory mode=0700

    
